/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package fibonacci;

public class App {
    public static void main(String[] args) {
        App app = new App();

        // Change number to whatever number you want to test your solution with
        long number = 10;
        System.out.println(app.fib(number));
    }

    // returns the number in the Fibonacci sequence
    public long fib(long n) {
        return n;
    }
}
