/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package fizzbuzz;

public class App {
    public static void main(String[] args) {
        System.out.println(new FizzBuzz().fizzbuzz(20));
    }
}
