/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package basics;

// Just general app class example
public class App {
    public static void main(String[] args) {
        System.out.println("Hello World");
    }
}
